project:
  type: website
  output-dir: docs
  preview: 
    port: 4200

  
  
website:
  title: "MSD" 
  site-url: ""
  repo-url: "" 

  search:
    type: overlay  
  page-footer:
    left: |
      Développé par 
      [![](https://raw.githubusercontent.com/fabbiocrux/Figures/main/Logos/ENSGSI/2022/Lorraine%20INP%20ENSGSI%20RS%20(couleur%2C%20CMJN).png){fig-alt="ENSGSI" width=65px}](https://www.ensgsi.univ-lorraine.fr/)
    center:
      - text: "About"
#        href: about.qmd
      - text: "FAQ"
#        href: docs/faq/index.qmd
      - text: "License"
#        href: license.qmd
      - text: "Trademark"
#        href: trademark.qmd
    right:
      - icon: twitter
        href: ""
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/fabbiocrux/MSD
        aria-label: Quarto GitHub
      - icon: rss
        href: https://quarto.org/docs/blog/index.xml
        aria-label: Quarto Blog RSS  
    background: light          

  navbar:
    background: light
    logo: cover.png
    logo-alt: "Quarto logo."
#    title: true
    collapse-below: lg
    left:
      - text: "Home"
        file: index.qmd    
      - text: "Cours Magistraux"
        file: CM.qmd    
      - text: "Travaux Dirigés"
        file: TD.qmd    
      - text: "Travaux Pratiques"
        file: TP.qmd            
      - text: "Aide"
        menu:
          - text: "Report un Erreur"
            icon: "bug"
#            href: "https://github.com/quarto-dev/quarto-cli/issues"
          - text: "Demandez une Question"
            icon: "chat-right-text"
#            href: "https://github.com/quarto-dev/quarto-cli/discussions"
          - text: "FAQ"
            icon: "question-circle"
#            href: docs/faq/index.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/fabbiocrux
        text: Quarto Twitter
      - icon: github
        href: https://github.com/fabbiocrux/MdP
        text: MdP GitHub
        
  sidebar:
    - title: "Cours Magistraux"
      style: "floating"
      contents:
        - CM.qmd      
        - CM/CM1.qmd
        - CM/CM2.qmd
        - CM/CM3.qmd
        - CM/CM4.qmd
        - CM/CM5.qmd        
        - CM/CM6.qmd                
    - title: "Travaux Dirigés"
      style: "floating"
      contents:
        - TD.qmd      
        - TD/TD1.qmd
        - TD/TD2.qmd
        - TD/TD3.qmd
#    - title: "Travaux Pratiques"
#      style: "floating"
#      contents:
#        - TP.qmd      
#        - TP/TP1.qmd
#        - TP/TP2.qmd        
#        - TP/TP3.qmd
#        - TP/TP4.qmd        
#        - TP/TP5.qmd
#        - TP/TP6.qmd        
#        - TP/TP7.qmd
#        - TP/TP8.qmd 
#        - TP/TP9.qmd                                        
  page-navigation: true
  back-to-top-navigation: true

format:
  html:
    theme:
      - litera
      - assets/custom.scss
    toc: true
    number-sections: true
    html-math-method: mathjax
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            loader: {
              load: ['[tex]/physics']
            },
            tex: {
              packages: {'[+]': ['physics']}
            }
          };
          </script>    
#      css: assets/styles.css  
  pdf:
    documentclass: article
    fontsize: 12pt
    number-sections: true
    keep-tex: false
    colorlinks: true
    geometry:
      - top=20mm
      - left=15mm
      - right=15mm
      - bottom=20mm 
    include-in-header:
      - file: "assets/latex.tex"

execute:
  cache: true
  echo: false
  #freeze: true

bibliography: references.bib
